- name: Upload to Modrinth
  uses: cloudnode-pro/modrinth-publish@1.0.0
  with:
    token: ${{ secrets.MODRINTH_TOKEN }}
    project: AABBCCDD
    file: target/ProjectName-${{ github.event.release.tag_name }}.jar
    changelog: ${{ github.event.release.body }}
    loaders: paper, spigot
    api-domain: api.modrinth.com
